### PR TITLE
Types: Add "pg" property to FastifyInstance

### PR DESCRIPTION
**Pull request by voxpelli**
As recommended in the guide for creating TypeScript compatible Fastify plugins, properties that the Fastify instances are decorated with should also in the types get added to those instances: https://www.fastify.io/docs/latest/TypeScript/#creating-a-typescript-fastify-plugin

This change follows up on #63 by adding that.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] <del>documentation is changed or added</del>
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by voxpelli** [comment]
Additional prior art: https://github.com/fastify/fastify-swagger/blob/6c17b3b13278dc663dc2d55c617fd3a77d0f0919/index.d.ts#L4-L26

**Review by mcollina — CHANGES_REQUESTED** [review]
Can you please add a unit test?

**Review by fox1t — APPROVED** [review]
Nice catch!

LGTM after adding tests.

**Comment by voxpelli** [comment]
This became more complex.

For some odd reason this module has an undocumented, yet tested and verified, capability that allows it to expose `fastify.pg` as either a `PostgresDb` directly or as a an object keyed with named database connections, each one containing a `PostgresDb`.

The latter is achieved by adding the module multiple times, each time adding a `name`.

So:

I changed course here a bit. Adding documentation for that property + tests that ensures that one always take one or the other approach.

Also clarified the intention that one should manually be adding the `pg` property to the `FastifyInstance` type.

Up next, in another PR, I would want to do a breaking change:

Have `fastify.pg` always be for a single db.
Have `fastify.pgMulti` (or similar name) always be for multiple db:s.

That way it's actually possible to expose types for both out of the box, without any users having to manually add the correct one for them.

How does that sound? Can we merge this PR as it is with the documentation and test improvements? And I'll open a new one that takes care of a possible breaking change.

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
