### PR TITLE
chore(gitignore): use latest github ignore template

### PR DESCRIPTION
**Pull request by Fdawgs**
Stop Yarn from sneaking in files

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by climba03003 — APPROVED** [review]
Should it apply to other repo as well ?

**Comment by Fdawgs** [comment]
> 
> 
> Should it apply to other repo as well ?

You've lost me there @climba03003, what do you mean?

**Comment by climba03003** [comment]
> 
> 
> > Should it apply to other repo as well ?
> 
> You've lost me there @climba03003, what do you mean?

Should other repo also need to update the `.gitignore` files like this one?

**Comment by Fdawgs** [comment]
> 
> 
> > > Should it apply to other repo as well ?
> > 
> > 
> > You've lost me there @climba03003, what do you mean?
> 
> @Fdawgs Should other repo also need to update the `.gitignore` files like this one?
> I think it is a very big duty to update all of them.

Ah yeah, it is a big job!
I'm happy to do them though, as I plan on reviewing all of the core Fastify plugins and pretty much doing housekeeping tasks like updating the `.gitignore` files and docs.

As long as people like yourself and @mcollina are happy to review the changes then I'll keep going!

**Pull request merged**
