### PR TITLE
Types: Actually add "pg" property to FastifyInstance (semi-breaking)

### PR DESCRIPTION
**Pull request by voxpelli**
Follow up to #68.

This actually adds `PostgresDb` as the type of `fastify.pg` by default – _and_ it adds `Record<string, PostgresDb>` as the default as well.

This means that anyone trying to access `fastify.pg` will get the correct types, with any additional property outside of the default ones being exposed as possible multi DB:s.

What do you think @mcollina @fox1t?

This definition will conflict with anyone who has made a local definition of the `fastify.pg` property, as was previously recommended, so from a types point of view this should probably require a `4.0.0` release?

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm, I'd be happy to land this in a semver-minor.

**Comment by mcollina** [comment]
I've seen types break in patch, minor and everything, as well as TS shipping breaking changes in minors. I'm not really concerned, the TS community is pretty loose on semver.

**Review by fox1t — APPROVED** [review]
I really like this implementation!
LGTM!

**Comment by fox1t** [comment]
I agree to ship this in a minor, as usual.

**Pull request merged**
